export const movieData = [
    {
        id:Math.random(),
        image: "https://fr.web.img3.acsta.net/medias/nmedia/18/35/23/40/18431141.jpg",
        date: "2005",
        type: "Comics",
        rating: 4,
        name: "Batman",
        description: "Bruce Wayne, alias Batman, est un super-héros de fiction appartenant à l'univers de DC Comics. ... Malgré sa réputation de héros solitaire, il sait s'entourer d'alliés, comme Robin, son majordome Alfred Pennyworth ou encore le commissaire de police James Gordon",
    },
    {
        id:Math.random(),
        image: "https://m.media-amazon.com/images/I/81+sTg6ZZyL._AC_SL1500_.jpg",
        date: "2000",
        type: "Histoire",
        rating: 5,
        name: "Gladitor",
        description: "Les gladiateurs sont des combattants qui s'affrontent généralement par paires bien définies, chacun des deux adversaires appartenant à une catégorie appelée armatura, dotée d'armes, d'une panoplie et de techniques de combat spécifiques",
    },
    {
        id:Math.random(),
        image: "https://m.media-amazon.com/images/M/MV5BMjI5NjcwMTQxMV5BMl5BanBnXkFtZTcwODg5ODkwNQ@@._V1_.jpg",
        date: "2004",
        type: "crime",
        rating: 3,
        name: "THE Punisher",
        description: "La série met en scène Frank Castle, alias le Punisher, un justicier qui combat le crime en tuant ses adversaires plutôt que de les livrer à la justice",
    },
    {
        id:Math.random(),
        image: "https://regionalpress.com/wp-content/uploads/2020/05/dachra-affiche-2.jpg",
        date: "2018",
        type: "Horreur", 
        rating: 1,
        name: "Dachra",
        description: "Yasmine, étudiante en journalisme, et ses deux amis Walid et Bilel qui cherchent à élucider le mystère d'un vieux crime, commis il y a plus de 25 ans.",
    },
    {
        id:Math.random(),
        image: "https://fr.web.img3.acsta.net/pictures/17/06/14/14/35/432174.jpg",
        date: "2017",
        type: "Action",
        rating: 3,
        name: "Sleepless",
        description: "Vincent Downs est un officier de police sous couverture qui se retrouve pris dans un réseau de policiers corrompus et de casinos clandestins à Las Vegas. Lorsqu'un braquage se passe mal, un groupe de criminels décide de kidnapper le fils de Down",
    },
]